---
name: Release

on:
  push:
    tags:
      - v*
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 
        with:
          fetch-depth: 0
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0 
        with:
          go-version: "1.23"
          cache: true

      - name: Run go-semantic-release
        uses: go-semantic-release/action@2e9dc4247a6004f8377781bef4cb9dad273a741f # v1.24.1
        id: semrel
        with:
          github-token: ${{ github.token }}
          changelog-generator-opt: emojis=true
          allow-initial-development-versions: true

      - name: Build and package
        if: steps.semrel.outputs.version != ''
        env:
          RELEASE_VERSION: ${{ steps.semrel.outputs.version }}
        run: |
          echo "Creating release version v${RELEASE_VERSION}"
          mkdir -p bin
          go test -v ./...
          go build -ldflags "-X main.version=v${RELEASE_VERSION}" -o bin/gh-attest-util .
          tar czf gh-attest-util.tar.gz bin/gh-attest-util

      - name: Upload binary artifact
        if: steps.semrel.outputs.version != ''
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: gh-attest-util
          path: bin/gh-attest-util

      - name: Login to GitHub Container Registry
        if: steps.semrel.outputs.version != ''
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        if: steps.semrel.outputs.version != ''
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.semrel.outputs.version }}
            ghcr.io/${{ github.repository }}:latest

      - name: Create Release
        if: steps.semrel.outputs.version != ''
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: gh-attest-util.tar.gz
          tag_name: v${{ steps.semrel.outputs.version }}
          generate_release_notes: true
          draft: false
          prerelease: false
          make_latest: true
