---
name: Release

on:
  push:
    tags:
      - v*
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 
        with:
          fetch-depth: 0
      - name: Run go-semantic-release
        uses: go-semantic-release/action@2e9dc4247a6004f8377781bef4cb9dad273a741f # v1.24.1
        id: go-semantic-release
        with:
          github-token: ${{ github.token }}
          changelog-generator-opt: emojis=true
          allow-initial-development-versions: true
      - name: Download binary artifact
        if: steps.go-semantic-release.outputs.version != ''
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: gh-attest-util
          path: bin
      - name: Upload Results/Sigstore Bundle as Release Asset
        if: steps.go-semantic-release.outputs.version != ''
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: |
            bin/gh-attest-util
          tag_name: v${{ steps.go-semantic-release.outputs.version }}
          token: ${{ github.token }}

